title: Guilherme Lemmi
description: Frontend developer at BairesDev and Javascript enthusiast
theme: jekyll-theme-cayman
avatar: https://avatars2.githubusercontent.com/u/571320?s=460&v=4

footer-links:
  email: guilhermelemmi@gmail.com
  github: guilhermelemmi
  linkedin: guilherme-lemmi
  stackoverflow: users/6605392/guilherme-lemmi
